# Site settings
title: H3R3T1C Blog
email: ldominguezvega@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Writing about the C/C++ programming, about Security, about Linux, about everythings.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://lfdominguez.github.io/" # the base hostname & protocol for your site
twitter_username: lfdominguez
github_username:  lfdominguez

# Build settings
markdown: kramdown

gems:
- jekyll-mentions
- jemoji
- jekyll-sitemap
- jekyll-feed
