# Site settings
# permalink: /:categories/:year/:month/:day/:title
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: rouge
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

future: true
jailed: false
gfm_quirks: paragraph_end

title: H3R3T1C Blog
email: ldominguezvega (AT) gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Writing about the C/C++ programming, about Security, about Linux, about everythings.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://lfdominguez.github.io/" # the base hostname & protocol for your site
twitter_username: lfdominguez
github_username:  lfdominguez

paginate: 5
paginate_path: "/page:num/"

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-smartify
  - jekyll_figure
  - jekyll-paginate
  - rouge

figures:
  dir: /images
  enumerate: true

smileytheme: MSN
